# Generated by Django 4.2.20 on 2025-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cover_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres_note', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
    ]
